
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const fmt=(n)=>"$"+(Math.round((+n||0)*100)/100).toFixed(2);
let CFG=null;const state={lines:[],selectedId:null,mode:"simple",terms:"",sowGlobal:"",discountPct:0,taxPct:0,depositPct:0};
const UNITS=["ea","yard","ton","hr","visit","app","lf","load","flat","sf","bag"];
async function loadCfg(){const res=await fetch("data/config.json",{cache:"no-store"});CFG=await res.json();return CFG;}
function ui(){document.body.innerHTML=`<header style="background:#1c7c3e;color:#fff;padding:10px 14px"><b id=brand>Scenic Roots — Quoter</b> <select id=actions style="float:right"><option>Actions…</option><option value=client>Client Proposal</option><option value=quote>Quick Quote Sheet</option><option value=form>Proposal Form</option><option value=png>Export PNG</option><option value=pdf>Export PDF</option></select></header><main style="padding:12px;max-width:1100px;margin:auto"><div id=controls></div><div id=rows></div><div id=out class=sheet></div></main>`;
 const c=$('#controls'); c.innerHTML=`<select id=catalog></select> <select id=qty><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select> <button id=add>Add</button> <span id=tot></span>`;
 const sel=$('#catalog'); sel.innerHTML='<option value="">Catalog…</option>'+ (CFG.categories||[]).map(cat=>`<optgroup label="${cat.name}">`+cat.items.map(i=>`<option value="${i.id}">${i.label} — ${i.unit} @ ${fmt(i.price)}</option>`).join('')+`</optgroup>`).join('');
 $('#add').onclick=()=>{const id=sel.value;if(!id)return;const it=(CFG.categories||[]).flatMap(c=>c.items).find(i=>i.id===id);const v=+$('#qty').value||1; addLine(it,v); render();};
}
function addLine(it,qty){const id=crypto.randomUUID(); state.lines.push({id,description:it.label,unit:it.unit,qty,priceEach:+it.price,photos:[],sow:""});state.selectedId=id;}
function render(){const rows=$('#rows'); rows.innerHTML='<div style="display:grid;grid-template-columns:40px 1.4fr .7fr .6fr .8fr .9fr 48px;gap:8px;font-weight:600;border-bottom:1px solid #ddd;padding:6px 0">#<span>Description</span><span>Unit</span><span>Qty</span><span>Price</span><span>Line $</span><span></span></div>'; state.lines.forEach((l,i)=>{const r=document.createElement('div'); r.style.display='grid'; r.style.gridTemplateColumns='40px 1.4fr .7fr .6fr .8fr .9fr 48px'; r.style.gap='8px'; r.style.alignItems='center'; r.style.padding='6px 0'; r.innerHTML=`<div>${i+1}</div><div>${l.description}</div><div>${l.unit}</div><div><input id="q${l.id}" type="number" value="${l.qty}" style="width:70px"></div><div><input id="p${l.id}" type="number" value="${l.priceEach}" style="width:90px"></div><div style="text-align:right">${fmt(l.qty*l.priceEach)}</div><div><button id="x${l.id}">🗑</button></div>`; rows.appendChild(r); $('#q'+l.id).onchange=e=>{l.qty=+e.target.value||1; render();}; $('#p'+l.id).onchange=e=>{l.priceEach=+e.target.value||0; render();}; $('#x'+l.id).onclick=()=>{state.lines=state.lines.filter(x=>x.id!==l.id); render();}; }); updateTotals();}
function updateTotals(){const subtotal=state.lines.reduce((s,l)=>s+l.qty*l.priceEach,0); $('#tot').textContent=' Total '+fmt(subtotal); }
function openView(kind){const out=$('#out'); out.innerHTML=''; const wrap=document.createElement('div'); wrap.id='view'; wrap.style.background='#fff'; wrap.style.border='1px solid #eee'; wrap.style.borderRadius='10px'; wrap.style.padding='10px'; wrap.innerHTML=`<h3>${CFG.business.name} — ${kind}</h3><table style="width:100%;border-collapse:collapse"><thead><tr><th align=left>Description</th><th align=right>Qty</th><th align=right>Unit</th><th align=right>Price</th><th align=right>Line $</th></tr></thead><tbody id=body></tbody></table>`; out.appendChild(wrap); const body=$('#body'); state.lines.forEach(l=>{const tr=document.createElement('tr'); tr.innerHTML=`<td>${l.description}</td><td align=right>${l.qty}</td><td align=right>${l.unit}</td><td align=right>${fmt(l.priceEach)}</td><td align=right>${fmt(l.qty*l.priceEach)}</td>`; body.appendChild(tr);});}
async function exportCurrent(kind){const el=$('#view')||document.body; const canvas=await html2canvas(el,{scale:2,backgroundColor:'#fff'}); const img=canvas.toDataURL('image/png'); if(kind==='png'){ const a=document.createElement('a'); a.href=img; a.download='quote.png'; a.click(); return;} const {jsPDF}=window.jspdf; const pdf=new jsPDF({orientation:'p',unit:'pt',format:'a4'}); const pageWidth=pdf.internal.pageSize.getWidth(); const ratio=canvas.width/canvas.height; const width=pageWidth-40, height=width/ratio; pdf.addImage(img,'PNG',20,20,width,height); pdf.save('quote.pdf'); }
function wire(){document.addEventListener('change',e=>{ if(e.target.id==='actions'){const v=e.target.value; if(v==='client') openView('Client Proposal'); if(v==='quote') openView('Quick Quote Sheet'); if(v==='form') openView('Proposal & Agreement'); if(v==='png') exportCurrent('png'); if(v==='pdf') exportCurrent('pdf'); }});}
loadCfg().then(()=>{ui();wire();});